---
# commandict CI yaml file

version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements.txt" }}

      - run:
          name: Installing package dependencies...
          command: |
            if [[ ! -f ../venv ]]; then
              python3 -m venv ../venv
              source ../venv/bin/activate
            fi
            ../venv/bin/pip install -r requirements.txt

      - save-cache:
          key: venv-{{ checksum "requirements.txt" }}
          paths: ../venv

      # Running test
      - run:
          name: Running test...
          command: |
            ../venv/bin/pytest
            ../venv/bin/flake8
            ../venv/bin/yamllint .circleci/config.yml

      - store_artifacts:
          path: test-reports
          destination: test-reports


workflows:
  version: 2
  test-then-build:
    jobs:
      - test
